import Head from 'next/head'
import Header from 'src/componets/Header'

export default function Home({ iconPath }: any) {
  return (
    <>
      <Head>
        <title>FoodJP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={iconPath} />
      </Head>
      <Header />
    </>
  )
}
