import Head from 'next/head'
import Header from 'src/componets/Header'

export default function Home({ one }: { one: number }) {
  return (
    <>
      <Head>
        <title>FoodJP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" />
      </Head>
      <Header />
      <h1>{one}</h1>
    </>
  )
}

export async function getStaticProps() {
  const one = 1
  return {
    props: { one },
  }
}
